
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/code_type_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: qa
  liquibase:
    database-change-log-table: CHANGELOG
    enabled: true
    user: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/code_type_db
    change-log: classpath:liquibase-changeLog.xml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/code_type_db
---
spring:
  config:
    activate:
      on-profile: database


---
