version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    ports:
    - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookstore_db
      MARIADB_USER: bookstore_app
      MARIADB_PASSWORD: bookstore_app